name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py38_1
  - anaconda-client=1.9.0=py38haa95532_0
  - anaconda-navigator=1.9.12=py38_0
  - anaconda-project=0.10.2=pyhd3eb1b0_0
  - argh=0.26.2=py38_0
  - argon2-cffi=20.1.0=py38h2bbff1b_1
  - asn1crypto=1.4.0=py_0
  - astroid=2.6.6=py38haa95532_0
  - astropy=4.0.1.post1=py38he774522_1
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.5.3=py_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.0=pyhd3eb1b0_2
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py38he774522_0
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - bitarray=2.3.0=py38h2bbff1b_1
  - bkcharts=0.2=py38_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - blosc=1.21.0=h19a0ad4_0
  - bokeh=2.4.1=py38haa95532_0
  - boto=2.49.0=py38_0
  - bottleneck=1.3.2=py38h2a96729_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.10.26=haa95532_2
  - certifi=2021.10.8=py38haa95532_0
  - cffi=1.15.0=py38h2bbff1b_0
  - cfitsio=3.470=he774522_6
  - chardet=4.0.0=py38haa95532_1003
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - comtypes=1.1.10=py38haa95532_1002
  - conda=4.10.3=py38haa95532_0
  - conda-build=3.18.11=py38_1
  - conda-env=2.6.0=1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.7.3=py38h8cc25b3_1
  - conda-verify=3.4.2=py_1
  - console_shortcut=0.1.1=4
  - contextlib2=0.6.0.post1=pyhd3eb1b0_0
  - cryptography=35.0.0=py38h71e12ea_0
  - curl=7.78.0=h86230a5_0
  - cycler=0.10.0=py38_0
  - cython=0.29.24=py38h604cdb4_0
  - cytoolz=0.11.0=py38he774522_0
  - dask=2021.10.0=pyhd3eb1b0_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distributed=2021.10.0=py38haa95532_0
  - docutils=0.17.1=py38haa95532_1
  - entrypoints=0.3=py38_0
  - et_xmlfile=1.1.0=py38haa95532_0
  - fastcache=1.1.0=py38he774522_0
  - filelock=3.3.1=pyhd3eb1b0_1
  - flake8=3.8.3=py_0
  - flask=2.0.2=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - fsspec=2021.10.1=pyhd3eb1b0_0
  - future=0.18.2=py38_1
  - get_terminal_size=1.0.0=h38e98db_0
  - gevent=21.8.0=py38h2bbff1b_1
  - giflib=5.2.1=h62dcd97_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmpy2=2.0.8=py38h7edee0f_3
  - greenlet=1.1.1=py38hd77b12b_0
  - h5py=2.10.0=py38h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.2=pyhd3eb1b0_0
  - imagecodecs=2021.8.26=py38ha1f97ea_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py38haa95532_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.4.1=py38haa95532_1
  - ipython=7.29.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.17.1=py38_0
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.0.6=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38haa95532_0
  - jupyter_server=1.4.1=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.8.2=pyhd3eb1b0_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=23.1.0=py38haa95532_0
  - kiwisolver=1.3.1=py38hd77b12b_0
  - krb5=1.19.2=h5b6d351_0
  - lazy-object-proxy=1.6.0=py38h2bbff1b_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libarchive=3.4.2=h5e25573_0
  - libcurl=7.78.0=h86230a5_0
  - libdeflate=1.8=h2bbff1b_5
  - libiconv=1.15=h1df5818_7
  - liblief=0.10.1=ha925a31_0
  - libllvm9=9.0.1=h21ff451_0
  - libopencv=4.0.1=hbb9e17c_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.2.0=hd0e1b90_0
  - libwebp=1.2.0=h2bbff1b_0
  - libxml2=2.9.12=h0ad7f3c_0
  - libxslt=1.1.34=he774522_0
  - libzopfli=1.0.3=ha925a31_0
  - llvmlite=0.37.0=py38h23ce68f_1
  - locket=0.2.1=py38haa95532_1
  - lxml=4.6.3=py38h9b66d53_0
  - lz4-c=1.9.3=h2bbff1b_1
  - lzo=2.10=he774522_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py38h2bbff1b_0
  - matplotlib=3.4.3=py38haa95532_0
  - matplotlib-base=3.4.3=py38h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py38_1
  - menuinst=1.4.16=py38he774522_1
  - mistune=0.8.4=py38he774522_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.1.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.10.0=pyhd3eb1b0_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.2.1=py38haa95532_0
  - msgpack-python=1.0.2=py38h59b6b97_1
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py38_0
  - munkres=1.1.4=py_0
  - navigator-updater=0.2.1=py38_0
  - nb_conda=2.2.1=py38_1
  - nb_conda_kernels=2.3.1=py38haa95532_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - nltk=3.6.5=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1006
  - notebook=6.4.6=py38haa95532_0
  - numba=0.54.1=py38hf11a4ad_0
  - numexpr=2.7.3=py38hcbcaa1e_0
  - numpy=1.18.5=py38h6530119_0
  - numpy-base=1.18.5=py38hc3f5095_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=pyhd3eb1b0_0
  - opencv=4.0.1=py38h2a7c758_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1l=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.0.5=py38h47e9c7a_0
  - pandoc=2.12=haa95532_0
  - pandocfilters=1.4.3=py38haa95532_1
  - paramiko=2.7.2=py_0
  - parso=0.7.0=py_0
  - partd=1.2.0=pyhd3eb1b0_0
  - path=16.0.0=py38haa95532_0
  - path.py=12.5.0=hd3eb1b0_0
  - pathlib2=2.3.6=py38haa95532_2
  - pathtools=0.1.2=pyhd3eb1b0_1
  - patsy=0.5.2=py38haa95532_0
  - pep8=1.7.1=py38_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py38hd45dc43_0
  - pip=21.2.2=py38haa95532_0
  - pkginfo=1.7.1=py38haa95532_0
  - pluggy=0.13.1=py38haa95532_0
  - ply=3.11=py38_0
  - powershell_shortcut=0.0.1=3
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.8.0=py38h2bbff1b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.10.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py38ha925a31_0
  - py-opencv=4.0.1=py38he44ac1e_0
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pycurl=7.44.1=py38hcd4344a_1
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pylint=2.9.6=py38haa95532_1
  - pynacl=1.4.0=py38h62dcd97_1
  - pyodbc=4.0.31=py38hd77b12b_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyreadline=2.1=py38_1
  - pyrsistent=0.18.0=py38h196d8e1_0
  - pysocks=1.7.1=py38haa95532_0
  - pytables=3.6.1=py38ha5be198_0
  - pytest=6.2.4=py38haa95532_2
  - python=3.8.3=he1778fa_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-jsonrpc-server=0.3.4=py_1
  - python-language-server=0.34.1=py38_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38he774522_2
  - pywin32=228=py38hbaba5e8_1
  - pywin32-ctypes=0.2.0=py38_1000
  - pywinpty=0.5.7=py38_0
  - pyyaml=6.0=py38h2bbff1b_1
  - pyzmq=22.2.1=py38hd77b12b_1
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - regex=2021.8.3=py38h2bbff1b_0
  - requests=2.26.0=pyhd3eb1b0_0
  - rope=0.21.1=pyhd3eb1b0_0
  - rtree=0.9.7=py38h2eaa2aa_1
  - ruamel_yaml=0.15.100=py38h2bbff1b_0
  - scikit-image=0.18.3=py38hf11a4ad_0
  - scikit-learn=1.0.1=py38hf11a4ad_0
  - scipy=1.5.0=py38h9439919_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38haa95532_0
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.7.0=pyhd3eb1b0_1001
  - sip=4.19.13=py38ha925a31_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=h33f27b4_0
  - sniffio=1.2.0=py38haa95532_1
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=4.2.0=pyhd3eb1b0_1
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=4.1.4=py38_0
  - spyder-kernels=1.9.2=py38_0
  - sqlalchemy=1.4.22=py38h2bbff1b_0
  - sqlite=3.36.0=h2bbff1b_0
  - statsmodels=0.11.1=py38he774522_0
  - sympy=1.9=py38haa95532_0
  - tbb=2021.4.0=h59b6b97_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.9.4=py38haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.11=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py38h2bbff1b_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - ujson=1.35=py38he774522_0
  - unicodecsv=0.14.1=py38_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=2.1.3=py38haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - win_unicode_console=0.5=py38_0
  - wincertstore=0.2=py38haa95532_2
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38he774522_1
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.2=pyhd3eb1b0_0
  - xlwings=0.24.9=py38haa95532_0
  - xlwt=1.3.0=py38_0
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=hd77b12b_0
  - zfp=0.5.5=hd77b12b_6
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zope=1.0=py38_1
  - zope.event=4.5.0=py38_0
  - zope.interface=5.4.0=py38h2bbff1b_0
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - anyio==3.3.0
    - deprecation==2.1.0
    - gif2numpy==1.3
    - jupyter-packaging==0.10.4
    - jupyter-server==1.10.1
    - jupyterlab==3.0.16
    - kaitaistruct==0.9
    - nbclassic==0.3.1
    - open3d==0.13.0
    - opencv-python==4.5.3.56
    - panda==0.3.1
    - requests-unixsocket==0.2.0
    - simpleaudio==1.0.4
    - sounddevice==0.4.1
    - soundfile==0.10.3.post1
    - tomlkit==0.7.2
    - websocket-client==1.1.0
    - wheel==0.36.2
prefix: D:\nir67\Anaconda\AnacondaFiles
